

development:
  adapter: postgresql
  encoding: unicode
  database: trail_master_development
  pool: 5
  username: fredericomorato
  password:
  timeout: 5000


test:
  adapter: postgresql
  encoding: unicode
  database: trail_master_test
  pool: 5
  username: fredericomorato
  password:
  timeout: 5000
